### PR TITLE
Adding basic html structure

### PR DESCRIPTION
**Pull request by NitkarshChourasia**
Just for testing purposes, adding a basic HTML structure to the repositories.
Please note the following improvements:

    Added a <meta> tag for character set and viewport.
    Included a brief description of the page in the <meta> tag.
    Used a meaningful <title> for the page.
    Added a reference to an external stylesheet (styles.css).
    Structured the HTML using <header>, <nav>, <main>, and <footer> sections.
    Used semantic HTML tags like <nav>, <section>, <header>, and <footer>.
    Linked navigation menu items with appropriate URLs.
    Included placeholders for potential about and contact pages.
    Added a simple footer with a copyright notice.
    Added a reference to an external JavaScript file (script.js) at the end of the body.

### CODE REVIEW

**Comment by NitkarshChourasia** [comment]
@sach2212 after reviewing do merge the commit, into.

**Comment by sach2212** [comment]
> Just for testing purposes, adding a basic HTML structure to the repositories. Please note the following improvements:
> 
> ```
> Added a <meta> tag for character set and viewport.
> Included a brief description of the page in the <meta> tag.
> Used a meaningful <title> for the page.
> Added a reference to an external stylesheet (styles.css).
> Structured the HTML using <header>, <nav>, <main>, and <footer> sections.
> Used semantic HTML tags like <nav>, <section>, <header>, and <footer>.
> Linked navigation menu items with appropriate URLs.
> Included placeholders for potential about and contact pages.
> Added a simple footer with a copyright notice.
> Added a reference to an external JavaScript file (script.js) at the end of the body.
> ```

assigning the proper class and ids like it should indicate the actual work

**Comment by NitkarshChourasia** [comment]
assigning the proper class and ids like it should indicate the actual work
How to do it?

**Comment by NitkarshChourasia** [comment]
> assigning the proper class and ids like it should indicate the actual work
How to do it?
Please explain me properly, what do you mean by actual work?

**Comment by sach2212** [comment]
like what we do in javascript we assign function name or variable name ,
like its indicating the work itself  (ex :- concatearray() like its showing what the actual work we have to do)
like wise in html we have to assign class and id's  (if we have to make a box give class name  'box', or if we want to make contact details use  name like 'contacts') for the better understanding
and  id we can't  assign again and again only 1 time but class we can

**Pull request merged**
